[hugoVersion]
extended = true
min = "0.90.1"

[[imports]]
path = "github.com/gohugoio/hugo-mod-bootstrap-scss/v5"

[[imports]]
path = "github.com/gethugothemes/hugo-modules/components/preloader"

[[imports]]
path = "github.com/gethugothemes/hugo-modules/images"

[[imports]]
path = "github.com/gethugothemes/hugo-modules/shortcodes/buttons"

[[imports]]
path = "github.com/gethugothemes/hugo-modules/shortcodes/codepen"

[[imports]]
path = "github.com/gethugothemes/hugo-modules/shortcodes/collapse"

[[imports]]
path = "github.com/gethugothemes/hugo-modules/shortcodes/notice"

[[imports]]
path = "github.com/gethugothemes/hugo-modules/shortcodes/video"

[[imports]]
path = "github.com/gethugothemes/hugo-modules/shortcodes/tabs"

[[imports]]
path = "github.com/gethugothemes/hugo-modules/shortcodes/image"

[[imports]]
path = "github.com/gethugothemes/hugo-modules/shortcodes/gallery"
